"use client";

import { Building2, Plus, Activity } from "lucide-react";
import { useBusinesses } from "../hooks/useBusiness";

export default function BusinessesPage() {
    const { businesses, loading, error, handleCreate, handleStatus, handleDelete, activeBusinesses, name, setName } = useBusinesses();

    return (
        <section
            className="
                relative
                overflow-hidden
                rounded-3xl
                border
                border-gray-200/80
                bg-white
                p-6
                md:p-8
                shadow-sm
            "
        >
            <div
                className="
                    absolute
                    -top-32
                    -left-32
                    h-64
                    w-64
                    rounded-full
                    bg-blue-50
                    blur-3xl
                "
            />
            <div
                className="
                    absolute
                    -bottom-32
                    -right-32
                    h-64
                    w-64
                    rounded-full
                    bg-indigo-50
                    blur-3xl
                "
            />
            <div className="relative z-10">
                <div
                    className="
                        flex
                        flex-col
                        md:flex-row
                        justify-between
                        gap-5
                        mb-8
                    "
                >
                    <div>
                        <h1
                            className="
                                flex
                                items-center
                                gap-3
                                text-2xl
                                font-bold
                                text-gray-900
                            "
                        >
                            <Building2
                                className="
                                    h-6
                                    w-6
                                    text-blue-600
                                "
                            />
                            Administración de Negocios
                        </h1>
                        <p
                            className="
                                mt-2
                                text-sm
                                text-gray-500
                            "
                        >
                            Gestiona los negocios registrados dentro de la plataforma.
                        </p>
                    </div>
                    <div
                        className="
                            inline-flex
                            items-center
                            gap-2
                            rounded-full
                            bg-blue-50
                            px-4
                            py-2
                            text-xs
                            font-semibold
                            text-blue-700
                            h-fit
                        "
                    >
                        <Activity className="w-4 h-4" />
                        {businesses.length} negocios registrados
                    </div>
                </div>
                <div
                    className="
                        grid
                        grid-cols-1
                        md:grid-cols-3
                        gap-4
                        mb-8
                    "
                >
                    <div
                        className="
                            rounded-2xl
                            border
                            border-gray-100
                            bg-white
                            p-5
                            shadow-sm
                        "
                    >
                        <p
                            className="
                                text-xs
                                font-semibold
                                text-gray-500
                            "
                        >
                            Total de negocios
                        </p>
                        <h2
                            className="
                                mt-2
                                text-3xl
                                font-bold
                                text-gray-900
                            "
                        >
                            {businesses.length}
                        </h2>
                    </div>
                    <div
                        className="
                            rounded-2xl
                            border
                            border-emerald-100
                            bg-emerald-50
                            p-5
                        "
                    >
                        <p
                            className="
                                text-xs
                                font-semibold
                                text-emerald-700
                            "
                        >
                            Activos
                        </p>
                        <h2
                            className="
                                mt-2
                                text-3xl
                                font-bold
                                text-emerald-700
                            "
                        >
                            {activeBusinesses}
                        </h2>
                    </div>
                    <div
                        className="
                            rounded-2xl
                            border
                            border-rose-100
                            bg-rose-50
                            p-5
                        "
                    >
                        <p
                            className="
                                text-xs
                                font-semibold
                                text-rose-700
                            "
                        >
                            Inactivos
                        </p>
                        <h2
                            className="
                                mt-2
                                text-3xl
                                font-bold
                                text-rose-700
                            "
                        >
                            {businesses.length - activeBusinesses}
                        </h2>
                    </div>
                </div>
                {
                    error && (
                        <div
                            className="
                                mb-8
                                flex
                                items-center
                                gap-4
                                rounded-2xl
                                border
                                border-red-200
                                bg-red-50
                                p-5
                            "
                        >
                            <div
                                className="
                                    flex
                                    h-10
                                    w-10
                                    items-center
                                    justify-center
                                    rounded-xl
                                    bg-red-100
                                    text-red-600
                                    font-bold
                                "
                            >
                                !
                            </div>
                            <div>
                                <p className="font-semibold text-red-700">
                                    Ha ocurrido un error
                                </p>
                                <p className="text-sm text-red-600">
                                    {error}
                                </p>
                            </div>
                        </div>
                    )
                }
                <div
                    className="
                        rounded-2xl
                        border
                        border-gray-100
                        bg-white
                        p-6
                        shadow-sm
                        mb-8
                    "
                >
                    <h2
                        className="
                            text-lg
                            font-bold
                            text-gray-900
                        "
                    >
                        Crear nuevo negocio
                    </h2>
                    <p
                        className="
                            mt-1
                            mb-5
                            text-sm
                            text-gray-500
                        "
                    >
                        Agrega un nuevo negocio que podrá utilizar la plataforma.
                    </p>
                    <form
                        onSubmit={handleCreate}
                        className="
                            flex
                            flex-col
                            md:flex-row
                            gap-4
                        "
                    >
                        <input
                            value={name}
                            onChange={(e) =>
                                setName(e.target.value)
                            }
                            placeholder="Nombre del negocio..."
                            className="
                                flex-1
                                rounded-xl
                                border
                                border-gray-200
                                px-4
                                py-3
                                text-sm
                                outline-none
                                transition-all
                                focus:border-blue-300
                                focus:ring-4
                                focus:ring-blue-100
                            "
                        />
                        <button
                            disabled={loading}
                            className="
                                inline-flex
                                items-center
                                justify-center
                                gap-2
                                rounded-xl
                                bg-blue-600
                                px-6
                                py-3
                                font-semibold
                                text-white
                                transition-all
                                hover:bg-blue-700
                                active:scale-95
                                disabled:opacity-50
                            "
                        >
                            <Plus className="w-4 h-4" />
                            Crear negocio
                        </button>
                    </form>
                </div>
                <div
                    className="
                        overflow-hidden
                        rounded-2xl
                        border
                        border-gray-100
                        bg-white
                        shadow-sm
                    "
                >
                    <div
                        className="
                            flex
                            items-center
                            justify-between
                            border-b
                            border-gray-100
                            px-6
                            py-5
                        "
                    >
                        <div>
                            <h2
                                className="
                                    text-lg
                                    font-bold
                                    text-gray-900
                                "
                            >
                                Negocios registrados
                            </h2>
                            <p
                                className="
                                    mt-1
                                    text-sm
                                    text-gray-500
                                "
                            >
                                Administra el estado de cada negocio.
                            </p>
                        </div>
                        <span
                            className="
                                rounded-full
                                bg-slate-100
                                px-4
                                py-2
                                text-xs
                                font-semibold
                                text-slate-600
                            "
                        >
                            {businesses.length} registros
                        </span>
                    </div>
                    {
                        businesses.length === 0 ? (
                            <div
                                className="
                                    flex
                                    flex-col
                                    items-center
                                    justify-center
                                    py-20
                                "
                            >
                                <Building2
                                    className="
                                        h-14
                                        w-14
                                        text-gray-300
                                    "
                                />
                                <h3
                                    className="
                                        mt-5
                                        text-lg
                                        font-semibold
                                        text-gray-800
                                    "
                                >
                                    No hay negocios registrados
                                </h3>
                                <p
                                    className="
                                        mt-2
                                        text-sm
                                        text-gray-500
                                    "
                                >
                                    Crea el primer negocio utilizando el formulario superior.
                                </p>
                            </div>
                        ) : (
                            <div className="overflow-x-auto">
                                <table className="min-w-full">
                                    <thead
                                        className="
                                            bg-gray-50
                                            border-b
                                            border-gray-100
                                        "
                                    >
                                        <tr>
                                            <th className="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">
                                                ID
                                            </th>
                                            <th className="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">
                                                Negocio
                                            </th>
                                            <th className="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">
                                                Estado
                                            </th>
                                            <th className="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">
                                                Creado
                                            </th>
                                            <th className="px-6 py-4 text-center text-xs font-semibold uppercase tracking-wide text-gray-500">
                                                Acciones
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {
                                            businesses.map((business) => (
                                                <tr
                                                    key={business.id}
                                                    className="
                                                        border-t
                                                        border-gray-100
                                                        transition-colors
                                                        hover:bg-slate-50
                                                    "
                                                >
                                                    <td
                                                        className="
                                                            px-6
                                                            py-5
                                                            font-mono
                                                            text-sm
                                                            text-gray-600
                                                        "
                                                    >
                                                        #{business.id}
                                                    </td>
                                                    <td
                                                        className="
                                                            px-6
                                                            py-5
                                                        "
                                                    >
                                                        <p
                                                            className="
                                                                font-semibold
                                                                text-gray-900
                                                            "
                                                        >
                                                            {business.name}
                                                        </p>
                                                    </td>
                                                    <td className="px-6 py-5">
                                                        {
                                                            business.status === "ACTIVE" ? (
                                                                <span
                                                                    className="
                                                                        inline-flex
                                                                        items-center
                                                                        rounded-full
                                                                        bg-emerald-50
                                                                        px-3
                                                                        py-1
                                                                        text-xs
                                                                        font-semibold
                                                                        text-emerald-700
                                                                    "
                                                                >
                                                                    Activo
                                                                </span>
                                                            ) : (
                                                                <span
                                                                    className="
                                                                        inline-flex
                                                                        items-center
                                                                        rounded-full
                                                                        bg-rose-50
                                                                        px-3
                                                                        py-1
                                                                        text-xs
                                                                        font-semibold
                                                                        text-rose-700
                                                                    "
                                                                >
                                                                    Inactivo
                                                                </span>
                                                            )
                                                        }
                                                    </td>
                                                    <td
                                                        className="
                                                            px-6
                                                            py-5
                                                            text-sm
                                                            text-gray-500
                                                        "
                                                    >
                                                        {
                                                            new Date(
                                                                business.createdAt
                                                            ).toLocaleDateString()
                                                        }
                                                    </td>
                                                    <td
                                                        className="
                                                            px-6
                                                            py-5
                                                        "
                                                    >
                                                        <div
                                                            className="
                                                                flex
                                                                justify-center
                                                                gap-2
                                                            "
                                                        >
                                                            <button
                                                                onClick={() =>
                                                                    handleStatus(
                                                                        business.id,
                                                                        business.status
                                                                    )
                                                                }
                                                                className="
                                                                    rounded-xl
                                                                    border
                                                                    border-amber-200
                                                                    bg-amber-50
                                                                    px-4
                                                                    py-2
                                                                    text-xs
                                                                    font-semibold
                                                                    text-amber-700
                                                                    transition-all
                                                                    hover:bg-amber-100
                                                                    active:scale-95
                                                                "
                                                            >
                                                                {
                                                                    business.status === "ACTIVE"
                                                                        ? "Desactivar"
                                                                        : "Activar"
                                                                }
                                                            </button>
                                                            <button
                                                                onClick={() =>
                                                                    handleDelete(
                                                                        business.id
                                                                    )
                                                                }
                                                                className="
                                                                    rounded-xl
                                                                    border
                                                                    border-red-200
                                                                    bg-red-50
                                                                    px-4
                                                                    py-2
                                                                    text-xs
                                                                    font-semibold
                                                                    text-red-700
                                                                    transition-all
                                                                    hover:bg-red-100
                                                                    active:scale-95
                                                                "
                                                            >
                                                                Eliminar
                                                            </button>
                                                        </div>
                                                    </td>
                                                </tr>
                                            ))
                                        }
                                    </tbody>
                                </table>
                            </div>
                        )
                    }
                </div>
            </div>
        </section>
    );
}